language: ruby
bundler_args: --path vendor/bundle
script: bundle exec rspec
cache: bundler
gemfile:
  - gemfiles/Gemfile.travis
before_install:
  - gem install bundler
  - bundle config --local without local_development yard guard
# env:
#   - "rack=1.3.4"
rvm:
  # 2.1, not 2.1.0 until fixed https://github.com/travis-ci/travis-ci/issues/2220
  - 2.1
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: 2.1
